version: "3.8"
services:
  localmongo1:
    hostname: mongo1
    image: mongo
    container_name: localmongo1
    expose:
    - 30001
    ports:
      - 30001:30001
    volumes:
        - data:/data
    networks:
      - MongoNet
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AngusM
    #   - MONGO_INITDB_ROOT_PASSWORD=M0catad1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "MongoSet", "--port", "30001" ]

  localmongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    expose:
    - 30002
    ports:
    - 30002:30002
    networks:
      - MongoNet
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AngusM
    #   - MONGO_INITDB_ROOT_PASSWORD=M0catad1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "MongoSet", "--port", "30002" ]
  localmongo3:
    hostname: mongo3
    image: mongo
    container_name: localmongo3
    expose:
    - 30003
    ports:
      - 30003:30003 
    networks:
      - MongoNet
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AngusM
    #   - MONGO_INITDB_ROOT_PASSWORD=M0catad1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "MongoSet", "--port", "30003" ]
  localmongo4:
    hostname: mongo4
    image: mongo
    container_name: localmongo4
    expose:
    - 30004
    ports:
      - 30004:30004 
    networks:
      - MongoNet
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AngusM
    #   - MONGO_INITDB_ROOT_PASSWORD=M0catad1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "MongoSet", "--port", "30004" ]
  localmongo5:
    hostname: mongo5
    image: mongo
    container_name: localmongo5
    expose:
    - 30005
    ports:
      - 30005:30005 
    networks:
      - MongoNet
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AngusM
    #   - MONGO_INITDB_ROOT_PASSWORD=M0catad1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "MongoSet", "--port", "30005" ]
  localmongo6:
    hostname: mongo6
    image: mongo
    container_name: localmongo6
    expose:
    - 30006
    ports:
      - 30006:30006 
    networks:
      - MongoNet
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=AngusM
    #   - MONGO_INITDB_ROOT_PASSWORD=M0catad1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "MongoSet", "--port", "30006"  ]
  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    depends_on:
      - localmongo1
      - localmongo2
      - localmongo3
    networks:
      - MongoNet
    restart: "no"

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=AngusM
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=M0catad1
  #     - ME_CONFIG_MONGODB_SERVER= mongodb://localmongo1:27017,localmongo2:27017,localmongo3:27017/?replicaSet=MongoSet  
volumes:
  data: {}

networks:
  MongoNet:
    name: MongoNet